In [6]:
import cv2
import numpy as np

# Function to compute the Gray Level Co-occurrence Matrix (GLCM)
def glcm(angle, image):
    rows = image.shape[0]
    cols = image.shape[1]
    dimension = np.max(image) + 1
    comatrix = np.zeros((dimension, dimension), dtype=np.uint8)

    print("Rows and Columns in co-occurrence matrix = ", dimension, "\n")
    print("Original image :-\n", image, "\n")

    if angle == 0:
        for a in range(0, rows):
            for b in range(0, cols - 1):
                x = image[a][b]
                y = image[a][b + 1]
                comatrix[x][y] += 1

    if angle == 90:
        for a in range(0, cols):
            for b in range(rows - 1, 0, -1):
                x = image[b][a]
                y = image[b - 1][a]
                comatrix[x][y] += 1

    if angle == 45:
        for a in range(0, rows):
            for b in range(0, cols):
                if a - 1 >= 0 and b + 1 < cols:
                    x = image[a][b]
                    y = image[a - 1][b + 1]
                    comatrix[x][y] += 1

    if angle == 135:
        for a in range(0, rows):
            for b in range(0, cols):
                if a - 1 >= 0 and b - 1 >= 0:
                    x = image[a][b]
                    y = image[a - 1][b - 1]
                    comatrix[x][y] += 1

    print("\n", "Final co-occurrence matrix :- \n", comatrix, "\n")
    cv2.imshow('Image', comatrix)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

    return comatrix

# Load the image
apple = cv2.imread(r'.\images\flowers.jpg')
print(apple)
cv2.imshow('Basket', apple)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Convert the image to grayscale
grayApple = cv2.cvtColor(apple, cv2.COLOR_BGR2GRAY)
print(grayApple)

# Compute GLCM for different angles
zero = glcm(0, grayApple)
ninety = glcm(90, grayApple)
forty5 = glcm(45, grayApple)
one35 = glcm(135, grayApple)

# Flatten each GLCM and concatenate them into a single column vector
zeroFlat = zero.flatten()
ninetyFlat = ninety.flatten()
forty5Flat = forty5.flatten()
one35Flat = one35.flatten()

a = np.concatenate((zeroFlat, ninetyFlat, forty5Flat, one35Flat), axis=0)
a.shape

a = a.reshape((260100, 1))
a.shape

print(a)

[[[  4  72  49]
  [  5  73  50]
  [  5  73  50]
  ...
  [  6  68  44]
  [  6  68  44]
  [  6  68  44]]

 [[  5  73  50]
  [  5  73  50]
  [  5  73  50]
  ...
  [  6  68  44]
  [  6  68  44]
  [  6  68  44]]

 [[  5  73  50]
  [  5  73  50]
  [  5  73  50]
  ...
  [  5  67  43]
  [  5  67  43]
  [  5  67  43]]

 ...

 [[ 15  72  51]
  [ 15  72  51]
  [ 15  72  51]
  ...
  [ 66 133  96]
  [ 66 133  96]
  [ 67 134  97]]

 [[ 15  72  51]
  [ 15  72  51]
  [ 15  72  51]
  ...
  [ 67 134  97]
  [ 67 134  97]
  [ 68 135  98]]

 [[ 15  72  51]
  [ 15  72  51]
  [ 15  72  51]
  ...
  [ 68 135  98]
  [ 68 135  98]
  [ 69 136  99]]]
[[ 57  58  58 ...  54  54  54]
 [ 58  58  58 ...  54  54  54]
 [ 58  58  58 ...  53  53  53]
 ...
 [ 59  59  59 ... 114 114 115]
 [ 59  59  59 ... 115 115 116]
 [ 59  59  59 ... 116 116 117]]
Rows and Columns in co-occurrence matrix =  255 

Original image :-
 [[ 57  58  58 ...  54  54  54]
 [ 58  58  58 ...  54  54  54]
 [ 58  58  58 ...  53  53  53]
 ...
 [ 59  59  