In [1]:
import numpy as np

image = np.array([[[10, 20, 30], [40, 50, 60], [70, 80, 90]], 
                  [[15, 25, 13], [0, 1, 2], [3, 4, 5]], 
                  [[90, 100, 65], [20, 45, 65], [100, 120, 30]]])

print(image)

x = image.shape
print(x)

# (a)
centre = image[1, 1, :]
print(centre)

# (b)
greenChannel = image[:, :, 1]
print(greenChannel)

# (c)
flatten = image.flatten()
print(flatten)
flatten.shape

flatten = []
for x in range(0, image.shape[0]):
    for j in range(0, image.shape[1]):
        for k in range(0, image.shape[2]):
            flatten.append(image[x, j, k])

print(flatten)

# (d)
newImage = np.random.randint(0, 255, size=(3, 3, 3))
print(newImage)

addArray = image + newImage
print(addArray)

[[[ 10  20  30]
  [ 40  50  60]
  [ 70  80  90]]

 [[ 15  25  13]
  [  0   1   2]
  [  3   4   5]]

 [[ 90 100  65]
  [ 20  45  65]
  [100 120  30]]]
(3, 3, 3)
[0 1 2]
[[ 20  50  80]
 [ 25   1   4]
 [100  45 120]]
[ 10  20  30  40  50  60  70  80  90  15  25  13   0   1   2   3   4   5
  90 100  65  20  45  65 100 120  30]
[10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 25, 13, 0, 1, 2, 3, 4, 5, 90, 100, 65, 20, 45, 65, 100, 120, 30]
[[[209  80 218]
  [ 46 137  19]
  [ 93   2 141]]

 [[250 231  38]
  [ 98  73  10]
  [158 163  78]]

 [[233 173  96]
  [ 51 145  15]
  [138  80 166]]]
[[[219 100 248]
  [ 86 187  79]
  [163  82 231]]

 [[265 256  51]
  [ 98  74  12]
  [161 167  83]]

 [[323 273 161]
  [ 71 190  80]
  [238 200 196]]]
